# Generated by Django 4.1.2 on 2022-11-12 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Washing_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.IntegerField()),
                ('building', models.CharField(max_length=1)),
                ('floor', models.IntegerField()),
                ('room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usage_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washing_machine.washing_machine')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_time', models.DateTimeField()),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='washing_machine.washing_machine')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
