# Generated by Django 4.1.2 on 2022-11-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='context',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
