# Generated by Django 4.1.2 on 2022-11-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorms', '0002_dormmate_offer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dormmate_offer',
        ),
    ]
